[theme]
primaryColor = "#00ffff"
backgroundColor = "#0a0a1f"
secondaryBackgroundColor = "#1a1a3f"
textColor = "#e0e0ff"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false 
